version: '3'

services:
  balaboba:
    image: fmgoncharov/ec2-balaboba
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      BOT_TOKEN: "${BOT_TOK}"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"