name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  create:
    ref_type: [tags]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: super-linter
        uses: github/super-linter@v4.8.5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}